### ISSUE TITLE
Question on solution 4: will "set-blocking, write, process.exit" work? Answer: nope

### ISSUE THREAD

**Issue by rationull** [joyent/node-exeunt#2]
The repo's readme states under Solution 4 "First, we can't just exit synchronously ... because that will synchronously call the exit syscall, and the process will terminate, before any IO handling to write buffered stdout/stderr" with an example. But (referring to that example) if it were OK in a given application to write some output to stdout/stderr between the setBlocking() and process.exit() calls then would that not trigger a blocking write and let us exit synchronously after flushing the two streams? Or does this solution rely specifically on the uv__io_poll() call in the event loop?

**Comment by trentm** [comment]
@rationull I added an example to play with this. My conclusion: If the stdout buffer is full (which it is if we have written >65k), then writes after `setBlocking` do NOT immediately get written. We still need another pass through the event loop (which is what exeunt() does).

Here are my example runs:

```
$ node write-65k-setblocking-write-and-exit.js | grep meta
[meta] start: writing 66560 bytes...
$ node write-65k-setblocking-write-and-exit.js | grep meta
[meta] start: writing 66560 bytes...
$ node write-65k-setblocking-write-and-exit.js | grep meta
[meta] start: writing 66560 bytes...
```

**Comment by rationull** [comment]
Well, that would settle it then. That seems to imply for Node more generally that even if you have stdout set to block that it won't actually always block until all output is flushed. Writing that much output all at once would be a very rare thing though.

**Comment by trentm** [comment]
@rationull I think that if one sets a stream stdout/stderr to blocking at the start of program execution (or at least before writing to it and filling up its buffer), then it might be a different story. Note this from libuv's docs:

```
.. c:function:: int uv_stream_set_blocking(uv_stream_t* handle, int blocking)

    Enable or disable blocking mode for a stream.

    When blocking mode is enabled all writes complete synchronously. The
    interface remains unchanged otherwise, e.g. completion or failure of the
    operation will still be reported through a callback which is made
    asynchronously.

    .. warning::
        Relying too much on this API is not recommended. It is likely to change
        significantly in the future.

        Currently only works on Windows for :c:type:`uv_pipe_t` handles.
        On UNIX platforms, all :c:type:`uv_stream_t` handles are supported.

        Also libuv currently makes no ordering guarantee when the blocking mode
        is changed after write requests have already been submitted. Therefore it is
        recommended to set the blocking mode immediately after opening or creating
        the stream.

    .. versionchanged:: 1.4.0 UNIX implementation added.
```

**Comment by rationull** [comment]
Thanks! I definitely need to do some spelunking into the Node and libuv source.
